### PR TITLE
Serve the whole folder of file instead of one html file

### PR DESCRIPTION
**Pull request by nathando**
Hi guys, 

Great work you guys have put together here! For my use case I would like to host the whole HTML5 app folder instead of a single file. Therefore, I've made some changes that allowed the server to be able to serve files as a simple nginx or apache server. 
This is useful when we consider the whole folder is the whole HTML5 app. If you guys think it's useful for other people, consider merge in. Thanks!
As an example, I has included in the **StreamingAssets** a open source mini game called `Hextris` as well

### CODE REVIEW

**Comment by nathando** [comment]
any comment, guys ?

**Comment by nathando** [comment]
@simonwittber can you review my PR for merging ?

**Comment by Moe-Baker** [comment]
Is their anyway I can download your pull request ? can't seem to find anyway for that

**Comment by nathando** [comment]
@Moe-Baker just go to my branch and download then https://github.com/nathando/uniwebserver

**Comment by Moe-Baker** [comment]
Thank you very much @nathando ! it works great.
I'd have had a brain seizure if I were to read the entire RFC standards doc just so I can send an image file lol.

**Pull request merged**
